### ISSUE TITLE
Use the uploader from a controller

### ISSUE THREAD

**Issue by erichonkanen** [benefitcloud/ember-uploader#100]
Hello,

I am currently using this as a component but I also have a use case where I want to use the EmberUploader.Uploader.create directly in a controller for a modal... is this possible?

Im adding the import to the top of my controller but it's not available in my controller...

`import EmberUploader from 'ember-uploader'`

**Comment by digitaltoad** [comment]
As long as you have imported it you should have access to it via `EmberUploader`. There isn't anything that makes this specific to one or the other.

**Comment by erichonkanen** [comment]
Ok yeah then something strange is going on... I am importing it just like that and it's not available from inside my controllers action...

**Comment by digitaltoad** [comment]
Do you have any example code you could show me?

**Comment by digitaltoad** [comment]
I think this was most likely a issue related to having to manually import ember-uploader via the `ember-cli-build.js`. I'm closing for right now as the newest version should just work.

**Comment by erichonkanen** [comment]
@digitaltoad ah forgot about this but I figured it out thanks!
