### ISSUE TITLE
Getting `Could not find module ember-import`

### ISSUE THREAD

**Issue by ekampp** [benefitcloud/ember-uploader#102]
Hi. 

I'm new to this ember stuff, so bare with me.

I'm trying to follow the guide in the Readme, trying to get ember-uploader to work on an ember 2.3 project. 

When I create the file-upload component, and add this code:

```
import Ember from 'ember';
import EmberUploader from 'ember-uploader';

export default EmberUploader.FileField.extend({
  url: '',
  filesDidChange: function(files) {
    var uploadUrl = this.get('url');

    var uploader = EmberUploader.Uploader.create({
      url: uploadUrl
    });

    if (!Ember.isEmpty(files)) {
      uploader.upload(files[0]);
    }
  }
});
```

Then I get this error in the console:

```
loader.js:164 Uncaught Error: Could not find module `ember-uploader` imported from `frontend/components/file-upload`
```

I have installed the [ember-uploader from the cli project](https://github.com/benefitcloud/ember-cli-uploader).

I'm guessing that I'm missing something where I need to somehow import the module from the cli installation? 

Any help is appreciated. 

Thanks in advance.

**Comment by villander** [comment]
@ekampp i have the same issue :(
My acceptance test say: `Error: Could not find module `ember-uploader` imported from `remoto/components/file-upload/component``

**Comment by villander** [comment]
@ekampp i have the same problem. But solved like this:

```
// ember-cli-build.js
app.import('bower_components/ember-uploader/dist/ember-uploader.min.js'); // Add this line!
```

**Comment by villander** [comment]
@digitaltoad i have added this information to the repository `ember-cli-uploader` follow my pull request

https://github.com/benefitcloud/ember-cli-uploader/pull/10

**Comment by ekampp** [comment]
Nice. Thanks @villander! :heart:

**Comment by digitaltoad** [comment]
I think these issues are related to the fact that I haven't updated this add on for Ember 2.x yet. I have a branch going that should resolve these issues but its been a while since I was able to work on it.

**Comment by villander** [comment]
@digitaltoad i think that no, this issues are related with `ember-cli` >= 1.3

**Comment by digitaltoad** [comment]
Thank you @villander
