### ISSUE TITLE
Allow nesting extra data sent with upload.

### ISSUE THREAD

**Issue by digitaltoad** [benefitcloud/ember-uploader#105]
Uploader currently only allows flat data to be sent with the upload.

**Comment by mikeLspohn** [comment]
I'm trying to figure out how to send extra data along with the file in the request to the api endpoint I'm uploading files to. Is there a way to add data to the payload being sent? If so, could a small example be shown in the docs?

**Comment by digitaltoad** [comment]
This has been added to the docs in the basic setup section.
