### ISSUE TITLE
duplicate uploads

### ISSUE THREAD

**Issue by adrianricardo** [benefitcloud/ember-uploader#107]
On first upload, my image uploads just fine. When I upload my second image, the first image is re-uploaded (along with the second image I selected). 

Gist - https://gist.github.com/adrianricardo/dd97dbb1767983f5aa16

Is there a way to clear out the selected images after being uploaded?

**Comment by digitaltoad** [comment]
The easiest way that will work in the most browsers is to recreate the file input on successful upload.

**Comment by andrei-sheina** [comment]
@digitaltoad any code example please?

**Comment by bradhaydon** [comment]
I would also appreciate a code example on how to recreate the file input.

**Comment by digitaltoad** [comment]
This is a way that we have done it before.

```handlebars
{{#if isUploading}}
    Uploading...
    {{progress-bar progress=progress}}
{{else}}
    {{#file-field files=file}}
      Upload
    {{/file-field}}
{{/if}}
```

**Comment by tinyweasel** [comment]
How do you pass the progress values into the progress-bar component?

**Comment by digitaltoad** [comment]
It depends on the component. You would want to grab the value from the progress event produced by the uploader, possibly bound to the controller. In the example I gave, the progress event from the uploader updates the progress on the controller which is then consumed by the progress component.
