### ISSUE TITLE
Send JSON payload not working

### ISSUE THREAD

**Issue by aalpizar** [benefitcloud/ember-uploader#108]
I'm trying to send data along with the url by extending Uploader and then creating it (I've seen this done in other issues). So I attempted to do something like this, but it is not sending the data correctly (400: Bad Request error). Is this the right syntax or am I missing something?

`````
`let uploader = EmberUploader.Uploader.extend({
          url: uploadUrl,
          ajaxSettings: function() {
            let settings = this._super.apply(this, arguments);
            settings.data = {
              id: id
            }
            return settings;
          }
        }).create();
``````

**Comment by digitaltoad** [comment]
Since Ember Uploader is using FormData, you would not be sending JSON with the request. Instead you will add extra data at the `upload` method.

```javascript
let uploader = EmberUploader.Uploader.extend({
  url: uploadUrl
}).create();

uploader.upload(fileToUpload, { id: id });
```

**Comment by aalpizar** [comment]
I tried that, still get this error `ember.debug.js:33408 Error: INTERNAL SERVER ERROR
    at __exports__.default.Ember.Object.extend.didError (ember-uploader.named-amd.js:235)`

when I step through the code, `data` seems to always be an empty `FormData` object.

**Comment by digitaltoad** [comment]
You cannot inspect `FormData` unless you are on Firefox using the `.entries` method. Can you inspect what your server side is receiving?

**Comment by aalpizar** [comment]
Would there be another way to send the data as FormData? Or it has to be like this `uploader.upload(file[0], {id: id})`

**Comment by digitaltoad** [comment]
It is like this because Ember Uploader is taking the object literal and appending it to the `FormData` object it creates for the upload request so that the file and data are sent at the same time. You could override `.createFormData` on the uploader to get access to the formData object and append data there but in that case, you are doing exactly what would have already been done for you using the `.upload` method. I should also point out that you can inspect what is being sent if you look at the request in something like the Chrome Developer Tools. From the looks of it, you also seem to be getting a `500` from your server.

**Comment by aalpizar** [comment]
So I'm passing in the data using the `uploader.upload(file[0], {id:id})` because you are right, there is not point in overriding the `.upload` method. So this is the way I create the uploader
```
let payload = { id: id };
let uploader = EmberUploader.Uploader.create({
          url: uploadUrl,
        });

    if (!Ember.isEmpty(files)) {
      uploader.upload(files[0], payload);
    }
```

This is what my payload data looks like in Chrome Dev Tools

```
------WebKitFormBoundaryVyWKaKkPLF0gERBX
Content-Disposition: form-data; name="id"

11
------WebKitFormBoundaryVyWKaKkPLF0gERBX
Content-Disposition: form-data; name="file"; filename="Screen Shot 2016-03-04 at 11.48.24 AM.png"
Content-Type: image/png


------WebKitFormBoundaryVyWKaKkPLF0gERBX--
```

The server side has the file, but doesn't have the payload data.

```
response = ThumbnailData.create(request.files['file'], loads(request.data))
(Pdb) request.data
''
(Pdb) request
<Request 'http://localhost:16542/thumbnailItems/' [POST]>
(Pdb) request.files
ImmutableMultiDict([('file', <FileStorage: u'Screen Shot 2016-03-04 at 11.48.24 AM.png' ('image/png')>)])
```

**Comment by digitaltoad** [comment]
Assuming you are using Flask. You want to use `request.form` as this is like a normal form payload and not a JSON payload.

**Comment by aalpizar** [comment]
Awesome, that did the trick. Thanks again (even though it wasn't really related to the uploader). You were a great help!

**Comment by digitaltoad** [comment]
Not a problem. Glad I could help.
