### ISSUE TITLE
Setting authentication headers issue

### ISSUE THREAD

**Issue by chrism** [benefitcloud/ember-uploader#113]
Hi,

I've followed the example given to set headers

```javascript
uploader = EmberUploader.Uploader.extend({
  url: 'api/v1/videos/' + videoUuid + '/' + assetTypePlural,
  ajaxSettings: function() {
    var settings = this._super.apply(this, arguments);
    settings.headers = {
      'Authorization': 'Bearer 123'
    };
    return settings;
  }
}).create();
```

but my POST request still looks like this:

![image](https://cloud.githubusercontent.com/assets/35488/14781863/9d1b32a6-0ae5-11e6-8b6b-81b093984ce5.png)

I was expecting to see `Authorization: Bearer 123` added to that list.

The reason I need to do this is that Ember Simple Auth has changed to require explicit authorization of requests now so I need to wrap the Uploader code like this.

```javascript

let uploader;

this.get('session').authorize('authorizer:myauthorizer', (headerName, headerValue) => {
  uploader = EmberUploader.Uploader.extend({
    url: 'api/v1/videos/' + videoUuid + '/' + assetTypePlural,
    ajaxSettings: function() {
      var settings = this._super.apply(this, arguments);
      settings.headers = {
        'Authorization': headerValue
      };
      return settings;
    }
  }).create();
});
```

Any ideas what is going wrong?

Note: I'm still on Ember 1.13.5 for now, so am getting the ember-uploader warning.

Many thanks.

**Comment by chrism** [comment]
I'm sorry, I missed you can set the headers like this

```javascript
export default EmberUploader.Uploader.extend({
  ajaxSettings: {
    headers: {
      'X-Application-Name': 'Uploader Test'
    }
  }
});
```

Which works perfectly!

**Comment by jacsebastien** [comment]
Hello, In which file are we supposed to do this?
