### ISSUE TITLE
Adding HTML accept attribute to component

### ISSUE THREAD

**Issue by ahakanergun** [benefitcloud/ember-uploader#119]
Hi, how can i add an input accept attribute to my file-uploader component.
I want to add .xlsx file accept attribute: accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

`{{ file-upload accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"  }} `

didn't work.

**Comment by digitaltoad** [comment]
Extend `EmberUploader.FileField` and add the accept attribute binding.

```js
import EmberUploader from 'ember-uploader';

export default EmberUploader.FileField.extend({
  attributeBindings: ['accept']
});
```

**Comment by ahakanergun** [comment]
oh, thanks @digitaltoad it works. I could't think of it.
