### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by BreonKnight** [benefitcloud/ember-uploader#120]
My name is Breon. I'm Ember uploader for a project and I'm wondering a few things.
1) Inside my model I have:  avatar: DS.attr('string'). What is the correct way to store the photos?

2) inside my HBS template i have as reads: {{file-upload url="/upload"}. Do I need a specific value to pull this photo to my controller?

3) Inside the controller I have: var avatar = this.get('url'). Is this correct?

My question is what is the correct way for me to send my data?

Thanks for your time,

Breon

**Comment by digitaltoad** [comment]
I'm not totally sure what you are asking here.

**Comment by BreonKnight** [comment]
literally asking when I use the ember uploader how do I pass it through to a controller

**Comment by digitaltoad** [comment]
`{{file-upload files=files url="/upload"}}` will bind to controller `files` which can then be observed.
