### ISSUE TITLE
Basic Setup Not Generating Input Field

### ISSUE THREAD

**Issue by yuschick** [benefitcloud/ember-uploader#126]
I am looking to do the basic setup to upload one image to me 'assets/...' directory. I have installed ember-uploader and created the file-upload component. In the component JS file, I have copied the basic setup example, leaving out the optional second argument. When I include the component in my form, no field is generated. Any help would be great.

**Comment by digitaltoad** [comment]
Are you still stuck with this? Sorry for the late response.

**Comment by yuschick** [comment]
No worries. I have since stopped looking at this so not actively stuck, no. If I dig back into it and hit the same snag I can let you know then. Thanks for getting back though!
