### ISSUE TITLE
How to upload a file based on a dynamic URL and have a upload button? [Question]

### ISSUE THREAD

**Issue by Yathi** [benefitcloud/ember-uploader#130]
I do not want the ember uploader to call, `upload` method as soon as the file is selected. I want to be able to click a button and have the `upload` method be called. I also want to supply the _URL_ dynamically when the 'upload' button is clicked. 

I am finding this a little hard to implement and if anyone could point me in the right direction, that wold be very helpful! 

Thanks!

**Comment by digitaltoad** [comment]
So as a contrived example.

#### app/routes/upload.js
```javascript
import Ember from 'ember';
import { Uploader } from 'ember-uploader/uploaders';

export default Ember.Route.extend({
  actions: {
    upload: function(files, url) {
      const uploader = Uploader.create({ url: url });
      uploader.upload(files);
    }
  }
});
```

#### app/components/file-field.js
```javascript
import { FileField } from 'ember-uploader/components';

export default FileField.extend({
  filesDidChange: function(files) {
    this.set('files', files);
  }
});
```

#### app/templates/upload.hbs
```handlebars
<div>
  {{file-field files=files}}
</div>
<div>
  {{input type="text" value=url placeholder="File upload url"}}
</div>
{{#if files}}
  <div>
    <button {{action "upload" files url}}>Upload</button>
  </div>
{{/if}}
```

**Comment by Yathi** [comment]
Thanks man! This was enough for me to get my code working!

**Comment by digitaltoad** [comment]
Glad I could help!
