### ISSUE TITLE
Custom template support

### ISSUE THREAD

**Issue by czosel** [benefitcloud/ember-uploader#132]
First of all, thanks for this awesome addon!

I had the requirement to add custom styling to the `<input type="file">`, and it seems that currently the best way to do this is through hiding the `input` element and wrapping it with a `label`, which is then styled (see [this answer on SO](http://stackoverflow.com/a/21842275/1743938)).

I got this to work with ember-uploader by extending the usual `Ember.Component` instead of `EmberUploader.FileField` and copying the following snippet from `FileField` into my component:
```
change (event) {
  const input = event.target
  if (!Ember.isEmpty(input.files)) {
    this.trigger('filesDidChange', input.files)
  }
},
```

This works great, but might not be the most beautiful way to solve it - it would be great to hear your thoughts on the matter.
- Should there be better support for custom templating? 
- Should this solution be documented?

Related: #88

**Comment by digitaltoad** [comment]
Why not just wrap the component? This is a template from one of our apps that uses `uploader`

```handlebars
<span class="button-file">
  {{#if icon}}
    <span class="icon icon-{{{icon}}}"></span>
  {{/if}}

  {{#if files}}
    Change
  {{else}}
    {{yield}}
  {{/if}}
  {{file-field files=files multiple=multiple disabled=disabled}}
</span>

{{#if showPreview}}
  <span class="fileupload-preview">
    <span class="icon icon-file-alt"></span>
    {{filePreview}}
    <a href="#" {{action "remove" target="view"}}>
      <span class="icon icon-remove icon-large"></span>
    </a>
  </span>
{{/if}}
```

**Comment by czosel** [comment]
Of course - can't believe i didn't think of that. 

Thank you!

**Comment by wuarmin** [comment]
It's important to note, that if you wrap the component you have to define the tagName in your wrapper-component!
