### ISSUE TITLE
Breaks for me using Ember 2.10.0

### ISSUE THREAD

**Issue by gobijan** [benefitcloud/ember-uploader#135]
Hi I upgraded to ember 2.10.0 and the uploader supporting multiple files broke for me.
Is Ember 2.10.0 supported?

**Comment by digitaltoad** [comment]
Multi file is still supported. Any examples?

**Comment by joneath** [comment]
Looks like the latest version changed how `isArray` works with FileLists which is breaking multi file upload support (falling to the else case starting at line 91 of uploaders/base.js). https://github.com/emberjs/ember.js/pull/12708

**Comment by joneath** [comment]
I've submitted a pull request here: https://github.com/benefitcloud/ember-uploader/pull/136

**Comment by gobijan** [comment]
To speed things up a bit (I need this in production):
https://github.com/benefitcloud/ember-uploader/pull/138

**Comment by digitaltoad** [comment]
Fixed with 62959a692157a81a253727c415698c7622c51d69
