### ISSUE TITLE
Translating string

### ISSUE THREAD

**Issue by javogel** [benefitcloud/ember-uploader#142]
Is it possible to translate the strings for this component? If its not a feature of this addon, is there a workaround I could use?

I need to translate both the "Choose file" and  "No file chosen" strings.

btw, thank you for this great addon.

**Comment by digitaltoad** [comment]
These strings are provided by the browser. Instead you could look at creating a style that hides the input under the facade of a button. http://geniuscarrier.com/how-to-style-a-html-file-upload-button-in-pure-css/

**Comment by javogel** [comment]
Thank you, @digitaltoad! On point.
