### ISSUE TITLE
S3 - The authorization mechanism you have provided is not supported.

### ISSUE THREAD

**Issue by rbarbour** [benefitcloud/ember-uploader#143]
I have set up my Rails API to return the appropriate response used to upload directly to AWS S3, but when I try to upload to S3, I get the below response back with a 400 error code.
<Code>InvalidRequest</Code>
<Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>
I am using the London, eu-west-2 region, and have added this to be returned in my JSON response so that the URL I am using for upload is https://s3-eu-west-2.amazonaws.com/BUCKET_NAME. 
Any help would be appreciated.
Thanks

**Comment by ValentinTrinque** [comment]
That's strange, I use it in one of my project, and it works. Here is what I am doing :

**Comment by rbarbour** [comment]
@ValentinTrinque You my friend are awesome. 
I was just missing the "{ "x-amz-algorithm" => "AWS4-HMAC-SHA256" }" in my policy. I had just copied the example from the wiki, and didn't realise that this option needed to be set. 
Much thanks

**Comment by ValentinTrinque** [comment]
@rbarbour All pleasure is mine !

**Comment by digitaltoad** [comment]
Thank you for the helpful response @ValentinTrinque.
