### ISSUE TITLE
S3 Upload currupting files

### ISSUE THREAD

**Issue by maxigs** [benefitcloud/ember-uploader#147]
Hi,

i'm currently trying to upload some files from a little EmberJS app with the ember-uploader. 
While the upload seems to work fine, all the files are corrupted on S3.

It seems that the stored files content type is form-data. Looking into the code of ember-uploader i see that it's submitting a form-data object to S3. I think this should be just the file itself?

Or do i overlook something in the documentation?

Thanks :)

**Comment by maxigs** [comment]
I really missed the part in the documentation where it says to use the other uploader, my bad 😊

**Comment by stevenwu** [comment]
@maxigs I'm having the same issue. How did you fix this? Thanks.

**Comment by maxigs** [comment]
I did actually use a different plug-in now, which i had to add s3 support to:

https://github.com/maxigs/ember-file-upload i didn't have the chance to make it a proper pull request yet to get it upstream, but it did work for when i tried it out like this.

**Comment by ezekg** [comment]
Just a quick solution for future reference to anyone who hits this issue:

```js
import EmberUploader from 'ember-uploader'
import Ember from 'ember'

const { Uploader } = EmberUploader
const { get, set } = Ember

const BinaryUploader = Uploader.extend({
  upload(file) {
    const url    = get(this, 'url')
    const method = get(this, 'method')

    set(this, 'isUploading', true)

    return this.ajax(url, file, method)
  }
})
```

Solving #163 would probably fix this issue as well.
