### ISSUE TITLE
Can't have two uploaders on the same page

### ISSUE THREAD

**Issue by kennethlarsen** [benefitcloud/ember-uploader#151]
It seems that if I have to components with `ember-uploader` displaying on the same page only the last added component actually works. The first gets the same settings as the last. Is this intended? It would be great to have support for multiple uploaders on the same page.

**Comment by jamesfid** [comment]
Hmm, are you using the `{{file-upload}}` component?  If so, I wonder if that's the root cause.  I have a custom component that leverages the `Uploader` from `ember-uploader` .  With this component, I am able to render it multiple times and each instance is functioning as intended.  I needed to make my own to handle drag-and-drop and more complex interactions. 

I might be able to help if you can give a bit more information (e.g. what do your templates look like).

**Comment by kennethlarsen** [comment]
I am using the `file-upload`, yes. 

```
import Ember from 'ember';
import EmberUploader from 'ember-uploader';
import ENV from '../config/environment';

export default EmberUploader.FileField.extend({
  filesDidChange(files) {
    const param = this.get('param');
    const uploader = EmberUploader.Uploader.create({
      url: `${ENV.APIHOST}/data_store/albums/${this.get('id')}/upload`,
      method: 'POST',
      paramName: param,
    });
    if (!Ember.isEmpty(files)) {
      uploader.upload(files[0]);
    }

    uploader.on('progress', (e) => {
      // Handle progress changes
      // Use `e.percent` to get percentage
      Ember.Logger.log(e.percent);
      this.set('uploadStatus', e.percent);
    });
  },
});
```
```
{{file-upload id=model.id uploadStatus=uploadStatus param="cover"}}
{{file-upload id=model.id uploadStatus=uploadStatus param="booklet"}}
```

**Comment by kennethlarsen** [comment]
You led me in the right direction so now it actually works. Thanks!

**Comment by digitaltoad** [comment]
To be clear, is there a bug using multiple instances of the file-upload component?

**Comment by kennethlarsen** [comment]
@digitaltoad If you follow the example in the documentation and use the ``{{file-upload}} that extends the uploader then it does not work with multiple instances.

**Comment by tinyweasel** [comment]
Can confirm if you use two instances of {{file-upload}} on the same page then only one works regardless of which one you put files in, unless you overwrite filesDidChange.
