### ISSUE TITLE
Easy way to work with a presigned Url?

### ISSUE THREAD

**Issue by peavers** [benefitcloud/ember-uploader#152]
My backend (using the aws java SDK) can return a presigned URL to use for PUT requests. 

This is a lot easier than trying to build up a response json request that ember-uploader is expecting; Is there an easy way of just plugging in my signed URL?

**Comment by peavers** [comment]
Wasn't able to figure this out so I wrote a microservice to handle signing and returning the object required by this addon. 

If anyone is interested it can be deployed as a standalone docker container or java service https://github.com/peavers/squid-service

**Comment by digitaltoad** [comment]
Sorry for the late response. You could just modify https://github.com/benefitcloud/ember-uploader/blob/master/addon/uploaders/s3.js#L41-L59 to take the expected result from the sign request.
