### ISSUE TITLE
Style to look like drag and drop

### ISSUE THREAD

**Issue by tinyweasel** [benefitcloud/ember-uploader#154]
Is it possible to style the component to look like a drag and drop box? And is there a standard way of changing the default "No file chosen" text?

**Comment by digitaltoad** [comment]
Styling would be left up to you so anything is possible. A quick search for Bootstrap file inputs (only because Bootstrap is so common) found this https://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3.

**Comment by tinyweasel** [comment]
Thanks! We're using material design so I'll have a look there. There's no way to change the default text though, no?

**Comment by digitaltoad** [comment]
This text is controlled by the browser. I would just use CSS to hide the input via it's opacity and then create my own label and update it when the input changes.

**Comment by tinyweasel** [comment]
Thanks! I'll try that.
