### ISSUE TITLE
Progress is always 100

### ISSUE THREAD

**Issue by tinyweasel** [benefitcloud/ember-uploader#156]
Tried to use the following code to create a progress bar but the percentage is always 100. Logging it to the console immediately logs 100, even if the file upload takes a few seconds. 
```
uploader.on('progress', e => {
  // Handle progress changes
  console.log(e.percent)
});
```

**Comment by digitaltoad** [comment]
Can you either put a break point at or override `didProgress` and let me know what you are getting for `loaded` and `total` from the event param?

```javascript
var Uploader = EmberUploader.Uploader.extend({
  didProgress: function(event) {
    this._super();
    console.log("Loaded: " + event.loaded);
    console.log("Total: " + event.total);
  }
});

**Comment by tinyweasel** [comment]
I tried overriding didProgress, but nothing got logged to console. Also, I have` EmberUploader.FileField`. Does that change things? I put a breakpoint at `console.log(e.percent)`, e.total and e.loaded are the same.

**Comment by digitaltoad** [comment]
Is this local or a remote server? Weird that`total` and `loaded` would be the same. Does the server support progress?

**Comment by tinyweasel** [comment]
Looks like the server doesn't support progress! Thanks for your help.
