### ISSUE TITLE
Enable preventDefault

### ISSUE THREAD

**Issue by tinyweasel** [benefitcloud/ember-uploader#159]
I've styled my component like this, so it looks like a drag and drop. The file upload works wherever you click on the drag and drop box, although the drag and drop has stopped working except when you drag directly into the input, which I've styled with the CSS from below, so you can't drag directly onto it. When you drag and drop onto the box, the file you are trying to upload opens in the browser. Is there a way of preventing that action so that the drag and drop upload will work in this way?

```
<label class="file-upload">
    {{file-upload filter=model.thisTab.id}}
    <span class="file-upload">Click or drag to choose a file to upload</span>
    <div class="mdl-progress mdl-js-progress mdl-progress__indeterminate hidden"></div>
</label>
```

```
label.file-upload input[type="file"] {
  position: fixed;
  top: -1000px;
}
span.file-upload {
  padding: 5% 0 5% 5%;
  background: #cacaca;
  border: 1px dashed black;
  width: 89%;
  margin: 3% 3% 0 3%;
  display: inline-block;
}
```

**Comment by digitaltoad** [comment]
You would do this in your `file-upload` component using the `dragOver` event.

**Comment by tinyweasel** [comment]
I couldn't seem to get that working, but I solved the problem by making the file input and the file-upload span the same size.
