### ISSUE TITLE
Looking for a maintainer.

### ISSUE THREAD

**Issue by digitaltoad** [benefitcloud/ember-uploader#170]
Benefitcloud no longer uses Ember and I don't have the time to continue working on this add-on. If anyone would like to take it over, please let me know.

**Comment by Dhaulagiri** [comment]
I would be interested insofar as I would like to help get this addon up to date as it is one of the only ones left in our app using babel 5.

Long term, though, I wonder if we wouldn't be better off combining forces with https://github.com/tim-evans/ember-file-upload and suggesting people migrate to it?  I _think_ they work relatively similarly, and the only reason I haven't changed to it in our app _yet_ is that it has a larger footprint payload-wize.

**Comment by snewcomer** [comment]
I would love to help push through features and bug fixes along with @Dhaulagiri if you don't mind giving write access.

I have yet to try see what replacing the same functionality I have w/ ember-file-upload yet, so not familiar with exactly what would need to happen...but would think a good path forward would be to get this addon up to date, fix bugs and eval if combining forces is a good idea.

**Comment by snewcomer** [comment]
@digitaltoad Pinging this again.  If possible, could you assign npm publish rights and such to me (and or @Dhaulagiri) when you have time?

**Comment by digitaltoad** [comment]
@snewcomer Sure thing. I have no problem letting the repo go somewhere else. I just want to verify the new maintainer(s).

**Comment by rwwagner90** [comment]
Were @snewcomer and @Dhaulagiri added as maintainers? We need to get this updated and off of bower and such.

**Comment by Dhaulagiri** [comment]
Not that I’m aware of

**Comment by snewcomer** [comment]
I'll be pushing up an upgrade PR today.

**Comment by rwwagner90** [comment]
@digitaltoad can we get some maintainers added here please?

@snewcomer nice, thanks for updating!

**Comment by industiger** [comment]
Josh @digitaltoad is taking some time off and will get back soon. I apologize for the wait.

**Comment by rwwagner90** [comment]
@industiger no problem. I would just love to help get this up to date and maintained, and it looks like several others are interested too 😄

**Comment by digitaltoad** [comment]
I'm going to go ahead and add @snewcomer and @Dhaulagiri as maintainers for now. If you want to talk about possibly moving the repo I'm fine with that as well.

**Comment by Dhaulagiri** [comment]
@digitaltoad are you still going to handle publishing to NPM or is that something we should be added to as well?

**Comment by digitaltoad** [comment]
Sorry I’ll add you there as well.
