### ISSUE TITLE
Setting headers is not working

### ISSUE THREAD

**Issue by sevkibaba** [benefitcloud/ember-uploader#181]
Hello,
First of all, thank you very much for your effort, it is very easy to use ember-uploader addon.

I came up with a code to make users upload images. However, I need to send an auth token. It is not working as it is expected. I used the code example in the ReadMe file. I am getting an authorization error when I add a file.
Here is my code:
``` javascript
export default EmberUploader.FileField.extend({
  session: service('session'),
  filesDidChange (files) {
    const uploader = EmberUploader.Uploader.extend({
      ajaxSettings: {
        headers: {
          'Authorization': 'Token ' + this.get('session.data.authenticated.token')
        }
      },
      url: (AppConfig.API.URL || '') + this.get('url')
    }).create();
    if (!isEmpty(files)) {
      uploader.upload(files[0]);
    }
  }
});
```

This might be related to ember version so here are some additional details:
ember-cli: 2.18.2
node: 8.11.3
os: linux x64
ember-uploader: 0.3.11

Do you have any idea what I might be doing wrong? Thanks in advance.
Cheers.

**Comment by danielspaniel** [comment]
all you have to do is:
```js
   const headers = {'Authorization': 'Token ' + this.get('session.data.authenticated.token')};
   const signingAjaxSettings = {headers};
   const uploader = S3Uploader.create({signingUrl, signingAjaxSettings});
```

**Comment by snewcomer** [comment]
@sevkibaba Depending on your codebase, it might be easy to update to `2.0.0`.  Also, I'm not 100% sure if the readme is compat with `0.3.11` as that was ~3 years ago.  

https://github.com/benefitcloud/ember-uploader/releases
https://github.com/benefitcloud/ember-uploader#modifying-the-request

**Comment by sevkibaba** [comment]
@danielspaniel Thanks Daniel but the code you gave is for S3 upload. Anyways, it's syntax is good looking and I decided to use it that way.

@snewcomer Thank you, I didn't realize that I was using an older version. I think it is caused because I used npm install. I installed the add-on again with ember install command and everything is working fine.

Cheers.
