### ISSUE TITLE
wrong variable (or need update doc) when you want to setting custom headers with extending s3 uploader

### ISSUE THREAD

**Issue by olenderhub** [benefitcloud/ember-uploader#182]
Good morning, 

In my case, I needed to extend s3 uploader with different headers.
In documentation is https://github.com/benefitcloud/ember-uploader#modifying-the-request

and it is fine when extending the uploader.js, but when you want to extend s3 uploader you have to 

```
signingAjaxSettings: {
  headers: {
    'X-Application-Name': 'Uploader Test'
  }
}
```

https://github.com/benefitcloud/ember-uploader/blob/01330b0b780c092d7ff8b38d0c311387bd01d3ec/addon/uploaders/s3.js#L70

**Comment by snewcomer** [comment]
@olenderhub Hey!  What is the problem + proposed solution?  Are you referring to this?

```
    const uploader = S3Uploader.create({
      signingAjaxSettings: {
        headers: {
          'X-Application-Name': 'Uploader Test'
        }
      }
    });
```

**Comment by olenderhub** [comment]
@snewcomer Thank you for the reply. Yes, with this it works. Firstly I thought if in doc is:

```
import Uploader from 'ember-uploader/uploaders/uploader';

export default Uploader.extend({
  ajaxSettings: {
    headers: {
      'X-Application-Name': 'Uploader Test'
    }
  }
});
```

so in s3 should be the same.

Solution1:
replace the name in https://github.com/benefitcloud/ember-uploader/blob/master/addon/uploaders/s3.js#L70

to `ajaxSettings` (which is in uploader.js)

solution2:

update doc, that if you want to pass different ajax settings extending the s3.js, you should use this syntax
```
 const uploader = S3Uploader.create({
      signingAjaxSettings: {
        headers: {
          'X-Application-Name': 'Uploader Test'
        }
      }
    });
```

Imho first solution is better.

btw. I am struggling with inject session service in my config file (for dynamic headers)

app/uploaders/s3-uploader.js

```
import S3Uploader from 'ember-uploader/uploaders/s3';
export default S3Uploader.extend({
session: service(),
(...)
});
```
@snewcomer do you have any idea how to deal with it?

**Comment by snewcomer** [comment]
For point 1, that might break ppl's apps.  So we would need to make it backwards compat or go with number 2 as you stated.

For the session piece, would something like this work?

```
export default FileField.extend({
  session: service(),

  filesDidChange(files) {
    const uploader = S3Uploader.extend({ session: this.session }).create();
  }
});
```

**Comment by olenderhub** [comment]
For point 1, yes that will break ppl's apps, when they update the addon. There is also 3 solution, create an alias and check firstly `ajaxSettings` then `signingAjaxSettings`, or just back to solution number 2.

Regards to session code. We don't use the FileField in a project (just old custom). I am updating (from "ember-cli-uploader": "^0.3.6", and refactoring old code - can't do next to change also with it).

So need to find something else. Thank you for a suggestion.

**Comment by snewcomer** [comment]
Yeah essentially the S3Uploader isn't built with the container, so you need to get the service off of something that is built with the container.  Will think about the header idea.  

Lmk if you have any other questions!
