### ISSUE TITLE
Authentication headers

### ISSUE THREAD

**Issue by artemgurzhii** [benefitcloud/ember-uploader#184]
I'm using `EmberUploader.Uploader` to send the file to the back-end server. But I didn't find any way to add `Authorization: Bearer TOKEN` header to the request.

**Comment by ezekg** [comment]
I think you need to add that into `ajaxSettings`. For example:

```js
import Uploader from 'ember-uploader/uploaders/uploader';

const uploader = Uploader.extend({
  ajaxSettings: {
    headers: {
      'Authorization': `Bearer ${TOKEN}`
    }
  }
})
```

**Comment by artemgurzhii** [comment]
@ezekg Yes, the problem was that I receive a token from the `session` service(`get(this, 'session.token')`) and I was a bit confused with [this example](https://github.com/benefitcloud/ember-uploader#modifying-the-request).
