### ISSUE TITLE
Sending additional data with upload to server

### ISSUE THREAD

**Issue by saarangsoltani** [benefitcloud/ember-uploader#23]
it could be great to send additional data along with the upload post/put request to the server. Most jquery upload plugins support this.
Consider this as  a proposal.

**Comment by tibotiber** [comment]
Hi! Has the readme been updated now? I'm trying to use this as follow:
```
uploader.upload(files[0], {'foo':'bar'}).then(...)
```
but the FormData object is always empty (I logged it to check its content just before submitting `return this._ajax(settings);`) in your code.
Any idea? Thanks.

**Comment by digitaltoad** [comment]
FormData cannot be inspected or logged per say. Check your server side instead.
