### ISSUE TITLE
Renaming files whilst saving them on S3

### ISSUE THREAD

**Issue by zac156** [benefitcloud/ember-uploader#26]
How could I rename a file while saving onto S3?

Currently I am generating a unique filename on the server when signing my S3 upload like this:

        return Response(
            {"acl": "public-read",
            "awsaccesskeyid": "ACCESSKEY",
            "bucket": "bucket",
            "policy": policy_encoded,
            "signature": signature,
            "key": "uploads/%s.%s" % (unique_filename, file_name_extension),
            })

"key" contains my unique filename and that saves the file correctly with the renamed filename.
The problem here is then getting that unique filename to my client, how could I work around this?

Thanks so much,

Zac

**Comment by selbyk** [comment]
Yeah, generating unique filenames on the server is how I've been doing it with the didSign event.  Can be closed
