### ISSUE TITLE
didUpload response is undefined

### ISSUE THREAD

**Issue by zac156** [benefitcloud/ember-uploader#31]
Hi, 

When I log the response here:

```javascript
uploader.on('didUpload', function(response) {
    console.log(response);
}
```
I get undefined. Why is this happening and is this the desired behaviour?

Thanks,

Zac

**Comment by digitaltoad** [comment]
I have not heard anything about this in a while. I'm going to close. If you continue to have issues, please reopen with details.

**Comment by Tuhaj** [comment]
hey, I got a this problem with then handler.
I get a response for success, but there is no response for failure.
```
      uploader.upload(file).then(function (response) {
          console.log(response); // some response
      }, function (response) {
        console.log(response); // no response
      });
```
