### ISSUE TITLE
Specifying Headers along with url

### ISSUE THREAD

**Issue by peyterkim** [benefitcloud/ember-uploader#35]
`export default Ember.FileField.extend({`
	`url: 'endpoint',`
        `headers: {}`
`});`

is this possible or some other way to do it?

**Comment by digitaltoad** [comment]
Uploader doesn’t use any headers associated with Ember Data. You will have to add the headers yourself. Use ```Ember.$.ajaxPrefilter``` for this.

-- 
Joshua Borton

On December 25, 2014 at 7:11:21 PM, Vladimir Dralo (notifications@github.com) wrote:

I also encountered some strange issue related headers.

I configured default headers to be used by Ember for auth users. Implementation looks like this:
http://emberjs.com/guides/models/connecting-to-an-http-server/#toc_custom-http-headers

It works fine everywhere except for file uploads. I've tried to lookup inside ember-uploader code, but I don't have enough experience to solve this.

Here are request headers from two diffetent post requests.
This one is fine (just example of successful requests):

Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch
Accept-Language:ru,en-US;q=0.8,en;q=0.6,uk;q=0.4
Authorization: Token token=THIS_ONE_IS_LOST
Connection:keep-alive
Content-Length:42
Content-Type:application/json; charset=UTF-8
Cookie: XXXXXXXXXXX
Host:192.168.1.29
Origin:http://192.168.1.29
Referer:http://192.168.1.29/3/edit
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
appid: ALSO_THIS_ONE_IS_SET_INSIDE_EMBER !!!!!!!!!!!!!!!!!!!!!!!!!!
X-CSRF-Token: XXXXXXXXXXX
X-Requested-With:XMLHttpRequest
This one is not (it's multipart/form-data sent with ember-uploader):

POST /api/v1/pictures HTTP/1.1
Host:192.168.1.29
Connection:keep-alive
Content-Length:124521
Origin:http://192.168.1.29
X-CSRF-Token:XXXXXXXXXXX
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryPghAlU95JAQhBeJm
Accept: */*
X-Requested-With: XMLHttpRequest
Referer: http://192.168.1.29/3/edit
Accept-Encoding:gzip, deflate
Accept-Language:ru,en-US;q=0.8,en;q=0.6,uk;q=0.4
Cookie:XXXXXXXXXXX

**Comment by lfridael** [comment]
```js
import EmberUploader from 'ember-uploader';

// Subclass
var CustomUploader = EmberUploader.Uploader.extend({

  headers: {},

  // Override
  _ajax: function(settings) {
    settings = Ember.merge(settings, this.getProperties('headers'));
    return this._super(settings);
  }

});

// Instantiate subclass
var uploader = CustomUploader.create({
   url: 'http://localhost:4200/upload-files',
   headers: {
     'header': 'value'
   }
});
```

**Comment by lfridael** [comment]
@digitaltoad `Ember.$.ajaxPrefilter` works globally for every Ember/jQuery-initiated request. Sometimes you need to customize headers just for the upload request.

One solutions would be to create a hook in `EmberUploader.Uploader` to customize the settings passed to `Ember.$.ajax`. This would cover more than just request headers.

```js
EmberUploader.Uploader.extend({

  // Overridable hook, by default changes nothing.
  ajaxSettings: function(settings) {
    return settings;
  },

  _ajax: function(settings) {
    settings = customizeSettings(settings);
    return this._ajax(settings);
  }

});
```

**Comment by tibotiber** [comment]
+1 on @lfridael's hook idea. Seems the most elegant! :)

**Comment by nextekcarl** [comment]
I'm in the same boat here. Don't want to modify all the request headers globally.

**Comment by digitaltoad** [comment]
I'm thinking that extracting user definable ajax settings that are then merged with the request is probably the best route for this. What do you guys think about this?

**Comment by nextekcarl** [comment]
That sounds exactly like what I need.

**Comment by joshuairl** [comment]
:+1:

**Comment by digitaltoad** [comment]
Guys checkout 721e0601c2e770f4e57001aea564282d0baf516f and let me know if this works for you.

**Comment by digitaltoad** [comment]
Still looking for some feedback on 721e060

**Comment by nextekcarl** [comment]
It looks good to me, though I had to write my own method for uploading files because of deadlines, so I won't be able to test this method myself.

**Comment by rami-alloush** [comment]
With `v2.0` there's no need for a `CustomUploader`, the following works for me

```javascript
      import Uploader from 'ember-uploader/uploaders/uploader';

      var uploader = Uploader.create({
        url: uploadUrl,
        ajaxSettings: {
          headers: {
            Authorization: 'Bearer ' + this.auth.get('accessToken'),
          },
        },
      });
```
