### ISSUE TITLE
Multiple file uploads

### ISSUE THREAD

**Issue by hellixir** [benefitcloud/ember-uploader#38]
Trying to make multiple file upload work, but with no success for now.
Is it working as intended?
Backend - Rails 4.2

``` javascript
App.FileUploadComponent = EmberUploader.FileField.extend
  multiple: true
  url: ''

  filesDidChange: ( ->
    uploadUrl = @get('url')
    files = @get('files')
    store = @get('targetObject.store')

    uploader = EmberUploader.Uploader.create
      url: uploadUrl
      paramName: 'image'

    if !Ember.isEmpty(files)
      uploader.upload(files, {'photo_set_id': @get('photoSetId')})

    uploader.on('progress', (e) ->
      console.log(e.percent)
    )

    uploader.on('didUpload', (data) ->
      store.pushMany('picture', data.pictures )
      store.update('photoSet', store.normalize('photoSet', data.photo_set) )
      )
  ).observes('files')
```

No matter what I do, Rails still receive only 1 file. Any ideas how to make it work?

**Comment by variousred** [comment]
@digitaltoad i'm still getting this issue with 0.3.9 ... not sure why

**Comment by variousred** [comment]
```if (Ember.isArray(files)) {``` never returns true. The upload method is only passed a single file at a time with ```uploader.upload(files[0]); // Uploader will send a sign request then upload to S3```
