### ISSUE TITLE
Integration with existing model libraries

### ISSUE THREAD

**Issue by digitaltoad** [benefitcloud/ember-uploader#48]
I want to talk about potentially integrating uploader with existing model libraries in Ember. For instance, allowing seamless uploads within ember data. There are already libraries which enable this with Ember Data, is this out of the scope of Uploader?

**Comment by koryteg** [comment]
I dont think there actually are any libraries that integrate with ember data model. if you know of one let me know please. this uploader is a pretty good solution for now. I am working around it by doing passing the resource name, id, property I am changing (ie avatar) to the server with the request and then doing reloading the records from the server

**Comment by digitaltoad** [comment]
Here is one that I found a few days ago by accident https://github.com/funtusov/ember-cli-form-data. I've always handled this in a way that the request itself didn't change, I just used the uploader for the request if the model contained an upload. I created uploader intentionally barebones.  Is there room for something like this in uploader or should there be a separate library that maybe has the whole kitchen sink?

**Comment by koryteg** [comment]
I feel like that would require reworking the entire library, so maybe it would be better to create another uploader that does ember data better. Side note. another feature that would be nice is to be able to customize the params format a bit more. and allow for nested params. ie. I am working with a rails backend and would like to pass the data in nested way like this:


    {
      id: "resource_id",
      resource_name: {
        attr1: "file1"
        attr2: 'file2'
        attr3: "file3"
      }
    }

**Comment by digitaltoad** [comment]
For nesting follow #105
