### ISSUE TITLE
"Failed to set the 'value'" with Ember 1.11

### ISSUE THREAD

**Issue by wagenet** [benefitcloud/ember-uploader#51]
> Uncaught InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

I was able to work around this issue by setting:

```js
  value: function(key, value) { // jshint ignore:line
    return "";
  }.property()
```

in the `FileField` component. This ensures the value is always set as an empty string.

**Comment by digitaltoad** [comment]
Looks like the FileField component needs some tests :disappointed: Mind throwing up a PR for this?

**Comment by wagenet** [comment]
I'll try to see if I can allocate some time for this. I'm wondering if extending `Ember.TextField` is worth it. Might make sense just to make a new standalone component.

**Comment by digitaltoad** [comment]
I'll take a look at that.-JoshOn Thu, Feb 12, 2015 at 12:42 PM,  benefitcloud/ember-uploader <reply@reply.github.com> wrote:            I'll try to see if I can allocate some time for this. I'm wondering if extending Ember.TextField is worth it. Might make sense just to make a new standalone component.

**Comment by digitaltoad** [comment]
Now using a component instead of extending `Ember.TextField`
