### ISSUE TITLE
progress-event with filename (for multiple:true)

### ISSUE THREAD

**Issue by dj-hedgehog** [benefitcloud/ember-uploader#53]
I'm filtering out everything which isn't an image before issuing the upload. Therefore I've got to trigger the upload-function multiple times.

Whenever I receive a `progress`-event there is no way I can figure out which file it belongs to. What can I do about this?

```
drop: function(e) {
    var files = e.dataTransfer.files;
    var acceptedFiles = []

    for(var i=0; i<files.length; i++){

      if (files[i].type==="image/jpeg" ||
          files[i].type==="image/gif" ||
          files[i].type==="image/png"){

        acceptedFiles.push(files[i])
      }

      acceptedFiles.forEach(function(singleFile) {
        uploader.upload(singleFile)
      })
    }
}

```

**Comment by digitaltoad** [comment]
From a quick glance, you could create a new uploader instance for each file. Then you would have separate events for each. This is still something that I'm struggling with in that I'm not sure the uploader itself should have state, in this case, progress.

**Comment by digitaltoad** [comment]
I should also add that multiple is not doing anything in this case as you are uploading the files individually.

**Comment by dj-hedgehog** [comment]
yeah, I tried uploading them all at once but there were errors when using a modified array.

**Comment by digitaltoad** [comment]
So does my first example work then? A separate uploader per file?

**Comment by digitaltoad** [comment]
Let me know if you still need help with this.

**Comment by mcfiredrill** [comment]
Had the same issue...
I tried looping over the files and creating a separate uploader instance for each file, like you suggested.
Seems to be working well so far, thanks for the tip. 👍
