### ISSUE TITLE
Resolving Promise Always True

### ISSUE THREAD

**Issue by gte451f** [benefitcloud/ember-uploader#54]
For some reason, my uploader is always sent to the success state when resolving the promise.  Could my server be returning the wrong results on error?

    var promise = uploader.upload(files);
    promise.then(function (data) {
        // Handle success
        // I am triggered even when the server returns error 500
    }, function (error) {
        // Handle failure
        // This is never triggered, even when the server fails
    });

**Comment by digitaltoad** [comment]
Have you checked to make sure that the status code is indeed a 500?

**Comment by digitaltoad** [comment]
If you still have problems, let me know.
