### ISSUE TITLE
didUpload gets triggered twice with s3 uploader

### ISSUE THREAD

**Issue by seifsallam** [benefitcloud/ember-uploader#57]
After updating `ember-uploder` I found that `didUpload` gets triggered twice. After signing file, then after actually uploading. Is this the correct behavior?

**Comment by digitaltoad** [comment]
Is this with the newest version? I just made updates a few days ago that I think fixes this problem.

**Comment by seifsallam** [comment]
Yeah, it's fixed, my bad :)
