### ISSUE TITLE
Is it safe to send awsaccesskey ?

### ISSUE THREAD

**Issue by ahmed1490** [benefitcloud/ember-uploader#61]
As part of the sign request an awk accesskey is sent to client.
I am afraid if someone can get hold of the key and use it to for eg, replace all files.

**Comment by digitaltoad** [comment]
I'm actually going to explore this more. When I initially implemented the S3 functionality, I took note from other libraries. I'm not so sure this is indeed the best way to do this. I will note that the access key used should not be one of root or a user with any roles outside of the ones needed to save a file.

**Comment by ahmed1490** [comment]
@digitaltoad Can you share what libraries do similarly?

**Comment by digitaltoad** [comment]
@ahmed1490 https://github.com/component/s3 is the first that comes to mind. I took inspiration from this library and its required https://github.com/component/upload to make ember uploader.

**Comment by ahmed1490** [comment]
Thanks @digitaltoad

**Comment by variousred** [comment]
Its not really a big deal, see: 
http://www.a2sdeveloper.com/page-do-i-need-to-keep-my-aws-access-key-id-secret.html
