### ISSUE TITLE
Error event?

### ISSUE THREAD

**Issue by lolmaus** [benefitcloud/ember-uploader#62]
Hi!

There are `progress` and `didUpload` event. What's missing is the `error` event.

**Comment by mike183** [comment]
Looks like it triggers a `didError` event when the XHR request fails, see [line 92 of uploader.js](https://github.com/benefitcloud/ember-uploader/blob/ea18d3ef346181f29e581562b24e3d6f434e1189/packages/ember-uploader/lib/uploader.js#L92)

**Comment by digitaltoad** [comment]
Thank you for replying to this @mike183. Closing for now. If there is a problem using this event, please let me know @lolmaus.
