### ISSUE TITLE
Usage question / ember-cli

### ISSUE THREAD

**Issue by DirkLachowski** [benefitcloud/ember-uploader#63]
When following the steps in "Basic setup":
- install via bower
- create file-upload component
- add code as suggested

i get

>  Error: Could not find module `ember-uploader` imported from `partner-admin/components/file-upload`

when opening a route containing a file-upload component in its template.
Obviously i'm missing something.

**Comment by digitaltoad** [comment]
Sorry are you using ember-cli?

**Comment by DirkLachowski** [comment]
Yes, ember-cli 0.2.3

**Comment by digitaltoad** [comment]
There is a cli addon for ember uploader called ember-cli-uploader. I would recommend using that as start as it includes this library. Next you must import ember-uploader anywhere you will be using it including extending the file component.



—
Josh

**Comment by quaertym** [comment]
I could not find this addon before so that I had created https://github.com/quaertym/ember-cli-ember-uploader , now I see that it is not necessary anymore, I will redirect users to ember-cli-uploader and deprecate it.

:+1: Thanks for the great work.

**Comment by DirkLachowski** [comment]
Doing  

    npm install --save-dev ember-cli-uploader
    ember generate ember-cli-uploader

gets me

> Unknown blueprint: ember-cli-uploader

**Comment by DirkLachowski** [comment]
Seems to be a doc thing, at least for ember-cli 0.2.3

I've changed

    npm install --save-dev ember-cli-uploader
    ember generate ember-cli-uploader

to 

    ember install ember-cli-uploader

That throws an error:

> The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

I then manually ran 

    ember generate ember-cli-uploader

and finally got a working addon.

**Comment by digitaltoad** [comment]
I'll look into this. Mind creating a issue on that repo?



—
Josh

**Comment by DirkLachowski** [comment]
Created as benefitcloud/ember-cli-uploader#2
Sorry for the delay.

**Comment by t0johnso** [comment]
If it's helpful, I had the same error initially. I had installed it while I was running my localhost/dev server. Once I restarted the ember-server it was fine. I think the localhost server didn't realize the new files were there yet.

TERMINAL:
I had already run ember-server 
Ctrl+C to stop in terminal,
double-checked that i was in the right directory,
ember-server
