### ISSUE TITLE
Import in Brocfile

### ISSUE THREAD

**Issue by jamiechong** [benefitcloud/ember-uploader#65]
Your README should mention that this line is required in `Brocfile.js`

`app.import('bower_components/ember-uploader/dist/ember-uploader.named-amd.js');`

**Comment by devinus** [comment]
:+1:

**Comment by digitaltoad** [comment]
Are you asking for install details when using Broccoli or is this inside a ember-cli project? If its the latter, there is a ember-cli addon for ember-uploader.

—
Josh

**Comment by devinus** [comment]
Oh, very nice! I didn't see that.

**Comment by holyxiaoxin** [comment]
I've tried following readme and still can't get it to work. I've even tried all the threads in the whole of issues. 

But I'm getting this error:

```Uncaught Error: Could not find module `ember-uploader` imported from `~/components/file-upload````

**Comment by quaertym** [comment]
This can be closed I guess.
