### ISSUE TITLE
Naming files?

### ISSUE THREAD

**Issue by Criten** [benefitcloud/ember-uploader#68]
Is there any way to set the name of a file when uploading to s3? If someone uploads a file the same time someone else is uploading a file of the same name but different content there will be a problem...

**Comment by digitaltoad** [comment]
The best way to handle this is on the server side to make sure you have a unique filename beforehand.


—
Josh

**Comment by Criten** [comment]
I'm going directly to a3 from the browser, so i don't have control over the
user's file names.

**Comment by digitaltoad** [comment]
You are still signing though correct?


—
Josh

**Comment by Criten** [comment]
Yea, do I sign it with the filename I want on a3 somehow?

**Comment by Criten** [comment]
Looks like you can name the file by changing the name attribute in the data object. [s3.js](https://github.com/benefitcloud/ember-uploader/blob/master/packages/ember-uploader/lib/s3.js#L45) Maybe we should allow a function that generates a name to be defined on the component so when the s3 upload command runs it can set the name.

```javascript
import Ember from 'ember';
import EmberUploader from 'ember-uploader';

export default EmberUploader.FileField.extend({
  url: '',

  // This function would get called to set the name of the file uploaded to s3
  // The name of the original file and the extension of the selected file will be passed
  fileName: function(name, ext) {
    return name + '-custom-name' + ext;
  },

  filesDidChange: (function() {
    ....
  }).observes('files')
});
```

Let me know what you think and I can try implementing it :)

Zack

**Comment by digitaltoad** [comment]
See #69
