### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by joshpfosi** [benefitcloud/ember-uploader#70]
Nevermind! Was being obtuse. Sorry for the spam.

**Comment by digitaltoad** [comment]
Instead of just a path, a full URL should work here.

—
Josh

**Comment by joshpfosi** [comment]
Yes, thanks for the incredibly fast response. I just put it together!

**Comment by digitaltoad** [comment]
Just a FYI, I haven’t updated the wiki yet, but its much easier to use the aws-sdk gem to do the signage instead of hand rolling it as the wiki would have you do.


—
Josh
