### ISSUE TITLE
ReferenceError: EmberUploader is not defined 

### ISSUE THREAD

**Issue by aloha202** [benefitcloud/ember-uploader#73]
Hey guys
I installed the cli version and after adding a component i have this error: ReferenceError: EmberUploader is not defined 
Can anyone help me with it? i think this should be simple
Thanks in advance

**Comment by NeoKuro** [comment]
Hi, how was this solved? I have the same issue, I've installed the dependencies (using bower), however it is giving me this error?

**Comment by digitaltoad** [comment]
You must import EmberUploader to use it.

```import EmberUploader from 'ember-uploader';```
