### ISSUE TITLE
Any plans for drag and drop support?

### ISSUE THREAD

**Issue by akshayrawat** [benefitcloud/ember-uploader#75]
It would be really useful to have Drag & Drop support. Are there any plans for it?

**Comment by digitaltoad** [comment]
I feel like this is probably outside of the scope of uploader. Even the file component seems like it should be somewhere else. After fixing some of the outstanding issues, I've had thoughts about throwing out another ember cli library that uses ember uploader but has all the UI bells and whistles to help people get moving faster.

**Comment by tinyweasel** [comment]
It does support drag and drop now.
