### ISSUE TITLE
can i send other params along with file??

### ISSUE THREAD

**Issue by santosh1994** [benefitcloud/ember-uploader#76]
@digitaltoad

**Comment by digitaltoad** [comment]
The ```upload``` method takes a file argument and a parameter object literal argument that is then combined before the upload takes place.

**Comment by santosh1994** [comment]
then how can i access it on server side

**Comment by digitaltoad** [comment]
https://github.com/benefitcloud/ember-uploader#change-namespace you can specify the parameter namespace and the parameter name for the file. Any extra data added via the object literal will use the keys as the parameter names. If a namespace is provided the data will be nested within that parameter namespace.

**Comment by santosh1994** [comment]
is there a option to cancel a upload request. If upload is on progress??

**Comment by santosh1994** [comment]
can i specify the file type in component so that other type of files will
not be able to select

**Comment by digitaltoad** [comment]
You'll have to handle that before upload.
