### ISSUE TITLE
How to use ember-uploader with express 4?

### ISSUE THREAD

**Issue by vikingmute** [benefitcloud/ember-uploader#83]
Hey,
I am using this with express 4, the plugin works fine.
but in my express endpoint, can't find the files I've been uploaded

I keep getting undefined for req.files, any idea?

**Comment by digitaltoad** [comment]
Sorry I haven't responded back to this. Are you still having trouble? What does your Uploader code look like?

**Comment by vikingmute** [comment]
@digitaltoad it seems there might be a bug with multer, your code should works fine. More details : https://github.com/expressjs/multer/issues/193
