### ISSUE TITLE
Min files removed

### ISSUE THREAD

**Issue by gsilis** [benefitcloud/ember-uploader#90]
https://github.com/benefitcloud/ember-uploader/commit/36234d2f76e281d93c3e2f995c1d70302f43ddd6 removes the minified files in `dist`. Is that an intentional change?

**Comment by digitaltoad** [comment]
That was not :(

I'll get it fixed in a few.

**Comment by digitaltoad** [comment]
Fixed in 387326aa8fabedbbd4c2c17dcf925e762c6b9fcc

**Comment by gsilis** [comment]
Thanks for the fix!
