### ISSUE TITLE
S3 enctype

### ISSUE THREAD

**Issue by lazybensch** [benefitcloud/ember-uploader#91]
Hi, I want to use ember-uploader to upload an image directly to S3, i copied the code from your README and signing with rails works fine, but when the component `POST`s the file to aws i get:
```
<Error>
<Code>PreconditionFailed</Code>
<Message>At least one of the pre-conditions you specified did not hold</Message>
<Condition>Bucket POST must be of the enclosure-type multipart/form-data</Condition>
...
</Error>
```
in a form submit i would set the enclosure-type like this: `<form enctype='multipart/form-data' ...>` How am I doing this for ember-uploader?

what i tried so far was overwriting the `ajaxSettings` method and setting `contentType: 'multipart/form-data'` instead of `false`, this solves the precondition error, but now i get:

```
<Error>
<Code>MalformedPOSTRequest</Code>
<Message>The body of your POST request is not well-formed multipart/form-data.</Message>
...
</Error>
```

To me it feels like this is a problem with the javascript `formData` object, but that would mean s3 upload should work for no one who is using this addon and i doubt that.

Did anyone ran into this issue before and knows whats up? or can someone point me to a working implementation somewhere ? im debugging this problem for +2 days now :(

**Comment by digitaltoad** [comment]
The guide in the wiki is a bit outdated. I now recommend instead using the http://www.github.com/aws/aws-sdk-ruby for signing. Did you get this figured out?

**Comment by varblob** [comment]
I'm actually poking at this at the moment, do you have an updated guide by any chance?

**Comment by digitaltoad** [comment]
I don't but I was messing around with it earlier today. Something like the following should work.

```ruby
require 'aws-sdk'
# This assumes you have ENV['AWS_REGION'] set to a valid aws region
# This also assumes you have ENV['AWS_S3_BUCKET'] set to a valid aws bucket
def sign
  resource = Aws::S3::Resource.new
  obj = resource.bucket(ENV['AWS_S3_BUCKET']).object(params[:name])
  json = obj.presigned_post(acl: 'public-read').fields
  # If you would like to send the endpoint back
  json['endpoint'] = obj.url
  render json: json
end
#...
```

**Comment by sevab** [comment]
`obj.url` throws a `NoMethodError` in 'aws-sdk', here's a corrected version:
```ruby
def sign
  resource = Aws::S3::Resource.new
  obj = resource.bucket(ENV['AWS_S3_BUCKET']).object(params[:name]).presigned_post(acl: 'public-read')
  json = obj.fields
  # If you would like to send the endpoint back
  json['endpoint'] = obj.url
  render json: json
end
```

**Comment by digitaltoad** [comment]
Ah thank you!

**Comment by ksykulev** [comment]
Also getting this error, for some reason the the `Content-Type` header in the request is not being set correctly..
```
POST / HTTP/1.1
Host: <host>
Connection: keep-alive
Content-Length: 7974
Pragma: no-cache
Cache-Control: no-cache
Accept: */*
Origin: http://localhost:4200
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36
*Content-Type: text/plain;charset=utf-8*
Referer: http://localhost:4200/....
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
```
When I manually create the form as html with all the data passed back from the sign request, and submit it as a full postback it uploads to s3 properly. Weird.. any ideas?

**Comment by digitaltoad** [comment]
Any possibility of seeing the code surrounding this?

**Comment by ksykulev** [comment]
@digitaltoad - Let me extract the relevant code into an ember app to share with you.

**Comment by ksykulev** [comment]
@digitaltoad - here is a sample ember app: https://github.com/ksykulev/extracted-file-upload
Let me know if this helps..

**Comment by digitaltoad** [comment]
Content-Type is set to false in the uploader.

**Comment by lukeclewlow** [comment]
Is there any way to override this? I am having the same error.

**Comment by lukeclewlow** [comment]
Found a way to over-ride, but seems this wasn't the problem. Leads me to get a 400 error -
````<Error>
<Code>MalformedPOSTRequest</Code>
<Message>The body of your POST request is not well-formed multipart/form-data.</Message>
<RequestId>9E04C5B3533A4957</RequestId>
<HostId>QIVJ/OH7gEpHIv28DDf+t6GsWrv+jYB2/44touDax2OUh5wIVKDhGL8upbfWedw7Y+Ooardopbo=</HostId>
</Error><Error>
<Code>MalformedPOSTRequest</Code>
<Message>The body of your POST request is not well-formed multipart/form-data.</Message>
<RequestId>9E04C5B3533A4957</RequestId>
<HostId>QIVJ/OH7gEpHIv28DDf+t6GsWrv+jYB2/44touDax2OUh5wIVKDhGL8upbfWedw7Y+Ooardopbo=</HostId>
</Error>

**Comment by digitaltoad** [comment]
That error is caused by overriding the content type.



—
Josh

**Comment by lukeclewlow** [comment]
So content-type should be set to text/plain;charset=UTF-8 when sending the POST request to S3?

**Comment by digitaltoad** [comment]
@ksykulev what browser are you testing in?

**Comment by ksykulev** [comment]
@digitaltoad - Chrome 47.0.2526.73

**Comment by digitaltoad** [comment]
There seems to be a bug in jQuery 2.1.4. Dropping back to jQuery 2.1.3 everything starts working for me. @lukeclewlow although the contentType setting for ajax is intended to be set to false as required by jQuery in order to prevent jQuery from automatically setting a content type, it should not be text/plain and instead should be multipart/form-data.

**Comment by lukeclewlow** [comment]
Thanks for looking into this @digitaltoad, however, dropping back to jQuery 2.1.3 doesn't seem to change anything for me. I am set up exactly how you suggest in the github readme, with jQuery 2.1.3 but still my request to amazon is sent as:

    Content-Type: text/plain;charset=UTF-8

So this should be automatically set by the browser?

**Comment by digitaltoad** [comment]
Embarrassing false positive. I’ll look at this more. The content-type should not be text/plain.

—
Josh

**Comment by digitaltoad** [comment]
Pretender is the culprit with this example app. I commented it out apparently at the same time that I changed the jQuery version which is why I couldn't see anything that would have changed in jQuery to cause this to fail.

**Comment by lukeclewlow** [comment]
Ah this is also the case for me. I am using ember-cli-mirage which uses pretender, to mock out my back end response. But this means you have to passthrough to reach Amazon. I get past this error if I don't use pretender/mirage. Thanks for all your help @digitaltoad.

**Comment by lazybensch** [comment]
yeah, thx @digitaltoad. at least i know where to troubleshoot now.
@lukeclewlow if you find a way to get this working with mirage, i would be grateful if you share your experience :D

**Comment by digitaltoad** [comment]
I actually just ran into this same issue working on the newest version of
uploader using mirage for testing. I assume the problem is that mirage
intercepts the request and although it is set to pass through, it does not have
access to the FormData contents like the browser does so the object is sent as
is. You may be able to mock out an object that allows you to parse the data back
out in mirage before passing through. I've done this in the current tests.

Josh
On Thu, Dec 10, 2015 at 4:20 AM, benefitcloud/ember-uploader
<reply@reply.github.com>
wrote:
yeah, thx @digitaltoad [https://github.com/digitaltoad] . at least i know where to troubleshoot now.
@lukeclewlow [https://github.com/lukeclewlow] if you find a way to get this working with mirage, i would be grateful if you
share your experience :D

—
Reply to this email directly or view it on GitHub
[https://github.com/benefitcloud/ember-uploader/issues/91#issuecomment-163542110] .[https://github.com/notifications/beacon/AABcH1jCth4lT_krZs8iVyOesNEkcytZks5pOTtvgaJpZM4GetJ8.gif]

**Comment by lazybensch** [comment]
i can confirm that it is a problem with mirage and @digitaltoad's last comment solves the issue.
i think you can close this issue =)
