### ISSUE TITLE
Unexpected field when using multer with express

### ISSUE THREAD

**Issue by wanxie** [benefitcloud/ember-uploader#95]
![screen shot 2015-12-22 at 3 48 59 pm](https://cloud.githubusercontent.com/assets/15738463/11968687/c1a0eec4-a8c3-11e5-8e0c-9eed88f7e6c3.png)

How do I remove [0] and [1] in name="file[0]" and name="file[1]" when uploading multiple files at the same time? Multer expects the fieldname to be just name="file" for all files when using multer().array('file', 2).

**Comment by digitaltoad** [comment]
This is a bug. Thank you for catching it.

**Comment by digitaltoad** [comment]
I'm working on fixing this in the [1.0.0-cleanup](/benefitcloud/ember-uploader/tree/1.0.0-cleanup) branch.

**Comment by digitaltoad** [comment]
This should be fixed in the latest master.
