### ISSUE TITLE
Upload canvas data to S3 (after image crop)

### ISSUE THREAD

**Issue by movstox** [benefitcloud/ember-uploader#96]
Hi all,

This is not an issue, though I'm looking for advice if it's possible to upload 'canvas data' (i.e. after image crop using HTML5 Canvas) to S3...

I can try submitting a pull request though need some help on where to look for solution.

Many thanks!

**Comment by digitaltoad** [comment]
I've actually never looked into this but I assume its pretty close to what I have in the tests to create a file on the fly. Take a look at [uploader_test.js](https://github.com/benefitcloud/ember-uploader/blob/master/packages/ember-uploader/tests/unit/uploader_test.js#L6-L13) to see if this helps.

**Comment by quaertym** [comment]
You can get canvas image as data and then convert it to blob. Once you have the blob you can upload it to S3.
```
var data = canvas.toDataURL('image/jpeg');
```
